[package]
name = "agent-music"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.1", features = ["full"] }
futures-lite = "1.12.0"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

platform = {path = "../../libraries/rust/platform/" }
music = {path = "../../libraries/rust/music/" }
base64 = "0.13.0"
